create table if not exists guests (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  city text not null check (city in ('Douala', 'Yaounde')),
  qr_data text,
  created_at timestamptz not null default now()
);

create index if not exists idx_guests_city on guests(city);
create index if not exists idx_guests_created_at on guests(created_at desc);

alter table guests enable row level security;

drop policy if exists guests_read on guests;
create policy guests_read on guests for select to anon using (true);

drop policy if exists guests_insert on guests;
create policy guests_insert on guests for insert to anon with check (
  length(trim(first_name)) between 1 and 100 and
  length(trim(last_name)) between 1 and 100 and
  city in ('Douala', 'Yaounde')
);

grant usage on schema public to anon;
grant select, insert on guests to anon;
