drop table if exists public.guests cascade;

create table public.guests (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  city text not null check (city in ('Douala', 'Yaounde')),
  qr_data text,
  created_at timestamptz not null default now()
);

create index idx_guests_city on public.guests(city);
create index idx_guests_created_at on public.guests(created_at desc);

alter table public.guests disable row level security;

grant usage on schema public to anon;
grant usage on schema public to authenticated;
grant select, insert on table public.guests to anon;
grant select, insert on table public.guests to authenticated;
grant usage, select on all sequences in schema public to anon;
grant usage, select on all sequences in schema public to authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'guests'
  ) then
    alter publication supabase_realtime add table public.guests;
  end if;
end $$;
